### PR TITLE
Update website with new name SigStore

### PR DESCRIPTION
**Pull request by axelsimon**
- replace Rekor with SigStore everywhere it makes sense
- add a note to warn people of the name change on pages explaining 'rekor' CLI tools
- move what is SigStore page to docs, add it to submenu
- more that i can't think of right now

Signed-off-by: axelsimon <github@axelsimon.net>

### CODE REVIEW

**Review by lukehinds — COMMENTED** [review]
thanks, this is going to need a bit more of a cherry picked rename as 'rekor' will remain the name of transparent log, but SigStore will be the overall outward name for what the org putw out brand wise

**Comment by axelsimon** [comment]
That's the idea i followed, so i never renamed rekor when it referred to the actual CLI tool, nor did i rename the "rekord" type, for instance.

That being said, i'll go over it again, with that idea in mind, separating both better along the lines of what you said.

**Comment by lukehinds** [comment]
> That's the idea i followed, so i never renamed rekor when it referred to the actual CLI tool, nor did i rename the "rekord" type, for instance.
> 
> That being said, i'll go over it again, with that idea in mind, separating both better along the lines of what you said.

I would not spend to much time on, i need to really revamp the whole thing as we have changed a lot since it was first put up.

**Comment by axelsimon** [comment]
Fair enough.
I think this PR puts the website in a state that makes sense wrt to the name change, and doesn't create extra confusion for readers. The only thing missing really is that the logo is still the Rekor logo.

**Pull request closed without merging**
